### ISSUE TITLE
Unable to run the code 

### ISSUE THREAD

**Issue by peermohtaram** [anushabvs/DeFraudNet-End2End-Fingerprint-Spoof-Detection-using-Patch-Level-Attention#2]
How to run this code? I have the dataset too but I am not able to figure out how can I run the code? what should be the directory structure of the dataset and code?

**Comment by peermohtaram** [comment]
where can I get the following files? what's the role of these files? can training be done without these files?

file_path = os.path.join(path,"image_type_classes.txt" )
    with open(file_path,'rb') as f:
      self.classes = pickle.load(f)
    file_path = os.path.join(path,"image_names.txt" )
    with open(file_path,'rb') as f:
      self.categories = pickle.load(f)
    file_path = os.path.join(path,"image_name_classes.txt" )
    with open(file_path,'rb') as f:
      self.authentication = pickle.load(f)
    file_path = os.path.join(path,"images.npy" )
    with open(file_path,'rb') as f:
      self.data= np.load(f)
    file_path = os.path.join(path,"image_type_class_no.npy" )
    with open(file_path,'rb') as f:
      self.classes_no = np.asarray(np.load(f))
    file_path = os.path.join(path,"image_auth_class_no.npy" )
    with open(file_path,'rb') as f:
      self.auth_no = np.load(f)

**Comment by anushabvs** [comment]
You don't need these files to train the network. This was just a form of dataloader used by us. You can load the data in whichever form convenient for you
